import { router } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Brand } from "../components/Brand";
import { GhostButton, PrimaryButton } from "../components/PrimaryButton";
import { Screen } from "../components/Screen";
import { colors } from "../lib/theme";
import { getNativeMeetingHistory, type NativeMeetingHistoryItem } from "../lib/meetingService";
import { meetingStateLabels } from "../lib/specs";

export default function HistoryScreen() {
  const [meetings, setMeetings] = useState<NativeMeetingHistoryItem[]>([]); const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  const loadHistory = async () => { setState("loading"); try { setMeetings(await getNativeMeetingHistory()); setState("ready"); } catch { setState("error"); } };
  useEffect(() => { void loadHistory(); }, []);
  const content = state === "loading" ? <View accessibilityRole="text" accessibilityLiveRegion="polite" accessibilityLabel="جارٍ تحميل سجل الجلسات" style={styles.stateCard}><ActivityIndicator color={colors.indigo} /><Text style={styles.stateText}>جارٍ تحميل سجل الجلسات…</Text></View> : state === "error" ? <View accessibilityRole="text" accessibilityLiveRegion="polite" accessibilityLabel="تعذر تحميل سجل الجلسات. أعد المحاولة." style={styles.stateCard}><Text style={styles.emptyTitle}>تعذر تحميل السجل</Text><Text style={styles.emptyText}>تحقق من الاتصال وتسجيل الدخول ثم أعد المحاولة.</Text><PrimaryButton title="إعادة المحاولة" onPress={() => void loadHistory()} /></View> : meetings.length === 0 ? <View accessibilityRole="text" accessibilityLiveRegion="polite" accessibilityLabel="لا توجد جلسات محفوظة بعد. أنشئ اجتماعًا جديدًا لتبدأ سجلًا منظّمًا لمحاضرك وإجراءات المتابعة." style={styles.empty}><Text style={styles.sparkle}>✦</Text><Text style={styles.emptyTitle}>لا توجد جلسات محفوظة بعد</Text><Text style={styles.emptyText}>أنشئ اجتماعًا جديدًا لتبدأ سجلًا منظّمًا لمحاضرك وإجراءات المتابعة.</Text><PrimaryButton title="بدء اجتماع جديد" onPress={() => router.push("/lobby")} /></View> : <View style={styles.list}>{meetings.map(meeting => meeting.status === "ended" ? <Pressable key={meeting.id} accessibilityRole="button" accessibilityLabel={`عرض محضر ${meeting.title}. انتهت.`} onPress={() => router.push({ pathname: "/minutes", params: { inviteCode: meeting.inviteCode, title: meeting.title } })} style={styles.meeting}><View><Text style={styles.meetingTitle}>{meeting.title}</Text><Text style={styles.meetingDate}>{formatHistoryDate(meeting.createdAt)}</Text></View><View style={styles.status}><Text style={styles.statusText}>انتهت</Text></View></Pressable> : <Pressable key={meeting.id} accessibilityRole="button" accessibilityLabel={`فتح ${meeting.title}. ${meetingStateLabels[meeting.status]}.`} onPress={() => router.push({ pathname: "/meeting", params: { inviteCode: meeting.inviteCode, title: meeting.title, share: "0" } })} style={styles.meeting}><View><Text style={styles.meetingTitle}>{meeting.title}</Text><Text style={styles.meetingDate}>{formatHistoryDate(meeting.createdAt)}</Text></View><View style={styles.status}><Text style={styles.statusText}>{meetingStateLabels[meeting.status]}</Text></View></Pressable>)}</View>;
  return <Screen><ScrollView contentContainerStyle={styles.content}><View style={styles.top}><GhostButton title="الرئيسية" onPress={() => router.replace("/")} /><Brand /></View><Text style={styles.eyebrow}>مساحتك الخاصة</Text><Text style={styles.title}>سجل الجلسات</Text><Text style={styles.subtitle}>ستظهر هنا الجلسات التي تنشئها من حسابك، مع محاضرها المحفوظة بعد موافقة المشاركين.</Text>{content}</ScrollView></Screen>;
}

function formatHistoryDate(value: Date | string | number) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "تاريخ غير متاح" : date.toLocaleDateString("ar-SA", { year: "numeric", month: "short", day: "numeric" }); }

const styles = StyleSheet.create({ content: { padding: 20, gap: 15 }, top: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, eyebrow: { color: colors.indigo, fontSize: 11, fontWeight: "900", textAlign: "right", marginTop: 20 }, title: { color: colors.ink, fontSize: 32, fontWeight: "900", textAlign: "right" }, subtitle: { color: colors.muted, fontSize: 14, lineHeight: 23, textAlign: "right" }, empty: { marginTop: 20, gap: 10, alignItems: "center", borderRadius: 24, borderWidth: 1, borderColor: colors.line, borderStyle: "dashed", backgroundColor: colors.surface, padding: 26 }, stateCard: { marginTop: 20, gap: 12, alignItems: "center", borderRadius: 24, backgroundColor: colors.surface, padding: 26 }, stateText: { color: colors.muted, fontSize: 13, fontWeight: "800" }, sparkle: { color: colors.indigo, fontSize: 28 }, emptyTitle: { color: colors.ink, fontSize: 17, fontWeight: "900" }, emptyText: { color: colors.muted, fontSize: 13, lineHeight: 21, textAlign: "center", marginBottom: 7 }, list: { marginTop: 12, gap: 10 }, meeting: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderRadius: 18, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface, padding: 15, gap: 12 }, meetingTitle: { color: colors.ink, fontSize: 15, fontWeight: "900", textAlign: "right" }, meetingDate: { color: colors.muted, fontSize: 11, marginTop: 5, textAlign: "right" }, status: { borderRadius: 99, backgroundColor: colors.lavender, paddingHorizontal: 9, paddingVertical: 6 }, statusText: { color: colors.indigo, fontSize: 10, fontWeight: "900" } });
