import { router } from "expo-router";
import { useEffect, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Brand } from "../components/Brand";
import { GhostButton, PrimaryButton } from "../components/PrimaryButton";
import { Screen } from "../components/Screen";
import { colors } from "../lib/theme";
import { getNativeMeetingHistory, type MeetingHistoryItem } from "../lib/meetingService";
import { getSessionToken, signInWithLinguaBridge } from "../lib/session";
import { getInviteSharingSessionParam } from "../lib/specs";
import { meetingStateLabels } from "@linguabridge/contracts/meetingSpecs";

export default function HistoryScreen() {
  const [items, setItems] = useState<MeetingHistoryItem[]>([]); const [loading, setLoading] = useState(true); const [needsLogin, setNeedsLogin] = useState(false); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { if (!(await getSessionToken())) { setNeedsLogin(true); return; } setNeedsLogin(false); setItems(await getNativeMeetingHistory()); } catch (next) { setError(next instanceof Error ? next.message : "تعذر تحميل السجل."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  return <Screen><ScrollView contentContainerStyle={styles.content}><View style={styles.top}><GhostButton title="الرئيسية" onPress={() => router.replace("/")} /><Brand /></View><Text style={styles.eyebrow}>مساحتك الخاصة</Text><Text style={styles.title}>سجل الجلسات</Text><Text style={styles.subtitle}>تظهر هنا جلسات حسابك فقط، مع محاضرها المتاحة بعد موافقة المشاركين.</Text>{loading ? <View style={styles.empty}><Text style={styles.emptyText}>جارٍ تحميل سجل الجلسات…</Text></View> : needsLogin ? <View style={styles.empty}><Text style={styles.emptyTitle}>سجّل الدخول لرؤية سجلك</Text><PrimaryButton title="تسجيل الدخول" onPress={() => void signInWithLinguaBridge()} /></View> : error ? <View style={styles.empty}><Text style={styles.emptyTitle}>تعذر تحميل السجل</Text><Text style={styles.emptyText}>{error}</Text><PrimaryButton title="إعادة المحاولة" onPress={() => void load()} /></View> : items.length ? <View style={styles.list}>{items.map(item => <Pressable key={item.inviteCode} onPress={() => router.push({ pathname: "/meeting", params: { title: item.title, inviteCode: item.inviteCode, share: getInviteSharingSessionParam(item.inviteSharingEnabled) } })} style={styles.item}><Text style={styles.itemStatus}>{meetingStateLabels[item.status]}</Text><Text style={styles.itemTitle}>{item.title}</Text><Text style={styles.itemDate}>{new Date(item.createdAt).toLocaleDateString("ar-SA")}</Text></Pressable>)}</View> : <View style={styles.empty}><Text style={styles.sparkle}>✦</Text><Text style={styles.emptyTitle}>لا توجد جلسات محفوظة بعد</Text><Text style={styles.emptyText}>أنشئ اجتماعًا جديدًا لتبدأ سجلًا منظّمًا لمحاضرك وإجراءات المتابعة.</Text><PrimaryButton title="بدء اجتماع جديد" onPress={() => router.push("/lobby")} /></View>}</ScrollView></Screen>;
}

const styles = StyleSheet.create({ content: { padding: 20, gap: 15 }, top: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, eyebrow: { color: colors.indigo, fontSize: 11, fontWeight: "900", textAlign: "right", marginTop: 20 }, title: { color: colors.ink, fontSize: 32, fontWeight: "900", textAlign: "right" }, subtitle: { color: colors.muted, fontSize: 14, lineHeight: 23, textAlign: "right" }, empty: { marginTop: 20, gap: 10, alignItems: "center", borderRadius: 24, borderWidth: 1, borderColor: colors.line, borderStyle: "dashed", backgroundColor: colors.surface, padding: 26 }, sparkle: { color: colors.indigo, fontSize: 28 }, emptyTitle: { color: colors.ink, fontSize: 17, fontWeight: "900" }, emptyText: { color: colors.muted, fontSize: 13, lineHeight: 21, textAlign: "center", marginBottom: 7 }, list: { gap: 10, marginTop: 10 }, item: { borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface, borderRadius: 18, padding: 15, gap: 5 }, itemStatus: { alignSelf: "flex-end", color: colors.indigo, fontSize: 11, fontWeight: "800" }, itemTitle: { color: colors.ink, fontSize: 16, fontWeight: "900", textAlign: "right" }, itemDate: { color: colors.muted, fontSize: 11, textAlign: "right" } });
