import { router } from "expo-router";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { Brand } from "../components/Brand";
import { GhostButton, PrimaryButton } from "../components/PrimaryButton";
import { Screen } from "../components/Screen";
import { colors } from "../lib/theme";

export default function HomeScreen() {
  return <Screen><ScrollView contentContainerStyle={styles.content}><View style={styles.top}><Brand /><GhostButton title="الإعدادات" onPress={() => router.push("/settings")} /></View><View style={styles.hero}><View style={styles.badge}><View style={styles.dot} /><Text style={styles.badgeText}>اجتماع واحد، فهم مشترك</Text></View><Text style={styles.title}>عندما تتحدث اللغات المختلفة، يبقى الحوار واضحًا.</Text><Text style={styles.body}>ترجمة فورية ونص حي ومحضر مرتب — بلغتك وبموافقة الجميع.</Text><PrimaryButton title="إنشاء اجتماع" onPress={() => router.push("/lobby")} /><View style={styles.row}><GhostButton title="انضمام برابط" onPress={() => router.push("/join" as never)} /><GhostButton title="سجل الجلسات" onPress={() => router.push("/history")} /></View></View><View style={styles.preview}><View style={styles.previewTop}><Text style={styles.live}>● جلسة مباشرة</Text><Text style={styles.person}>مايا حداد</Text></View><View style={styles.speaker}><Text style={styles.language}>العربية ← English</Text><Text style={styles.bars}>▁▃▆█▅▂</Text></View><View style={styles.translations}><View style={styles.original}><Text style={styles.smallLabel}>الأصل</Text><Text style={styles.arabic}>أقترح أن نبدأ بنطاق الإطلاق، ثم نراجع المراحل مع الفريق.</Text></View><View style={styles.translated}><Text style={styles.smallLabel}>TRANSLATION</Text><Text style={styles.english}>I suggest we start with the launch scope, then review the milestones.</Text></View></View></View><View style={styles.features}><Text style={styles.feature}>موافقة واضحة قبل الحفظ</Text><Text style={styles.feature}>لغات واتجاهات متعددة</Text><Text style={styles.feature}>محضر قابل للتصدير</Text></View></ScrollView></Screen>;
}

const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 36, gap: 24 }, top: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, hero: { paddingTop: 14 }, badge: { alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 6, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, paddingHorizontal: 10, paddingVertical: 7, borderRadius: 99 }, dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: colors.success }, badgeText: { color: colors.ink, fontSize: 11, fontWeight: "700" }, title: { color: colors.ink, fontSize: 37, lineHeight: 47, fontWeight: "900", letterSpacing: -1.1, textAlign: "right", marginTop: 18 }, body: { color: colors.muted, fontSize: 16, lineHeight: 27, textAlign: "right", marginTop: 13, marginBottom: 22 }, row: { flexDirection: "row", gap: 10, marginTop: 11 }, preview: { borderRadius: 26, backgroundColor: "#1E245A", padding: 15, gap: 12 }, previewTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, live: { color: "#A7F3D0", fontSize: 11, fontWeight: "800" }, person: { color: "white", fontSize: 13, fontWeight: "800" }, speaker: { backgroundColor: "rgba(255,255,255,0.11)", borderRadius: 16, padding: 13 }, language: { color: "#CBD5FF", fontSize: 11 }, bars: { marginTop: 8, color: "#5EEAD4", fontSize: 20, letterSpacing: 2 }, translations: { flexDirection: "row", gap: 9 }, original: { flex: 1, minHeight: 112, borderRadius: 15, backgroundColor: "white", padding: 12 }, translated: { flex: 1, minHeight: 112, borderRadius: 15, backgroundColor: "#E9EAFE", padding: 12 }, smallLabel: { color: "#7277B9", fontSize: 9, fontWeight: "900" }, arabic: { color: colors.ink, fontSize: 13, lineHeight: 21, textAlign: "right", marginTop: 9, fontWeight: "600" }, english: { color: colors.ink, fontSize: 12, lineHeight: 18, textAlign: "left", marginTop: 9, fontWeight: "700" }, features: { gap: 9, marginTop: 2 }, feature: { color: colors.muted, fontSize: 12, textAlign: "center" } });
