import { router } from "expo-router";
import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { GhostButton, PrimaryButton } from "../components/PrimaryButton";
import { Screen } from "../components/Screen";
import { meetingPrivacyDefaults, supportedLanguages } from "../lib/specs";
import { colors } from "../lib/theme";

export default function SettingsScreen() { const [language, setLanguage] = useState("ar"); const [storage, setStorage] = useState<boolean>(meetingPrivacyDefaults.confirmStoragePerMeeting); const [reminders, setReminders] = useState<boolean>(meetingPrivacyDefaults.meetingReminders); return <Screen><ScrollView contentContainerStyle={styles.content}><View style={styles.top}><GhostButton title="العودة" onPress={() => router.back()} /><Text style={styles.eyebrow}>حسابك</Text></View><Text style={styles.title}>الإعدادات الشخصية</Text><Text style={styles.subtitle}>اضبط لغتك الافتراضية والصوت وطريقة التعامل مع محتوى جلساتك.</Text><View style={styles.card}><Text style={styles.cardTitle}>اللغة والترجمة</Text><View style={styles.choices}>{supportedLanguages.map(item => <Pressable key={item.code} onPress={() => setLanguage(item.code)} style={[styles.choice, language === item.code && styles.selected]}><Text style={[styles.choiceText, language === item.code && styles.selectedText]}>{item.label}</Text></Pressable>)}</View></View><View style={styles.card}><Text style={styles.cardTitle}>الصوت والأجهزة</Text><Text style={styles.note}>سيستخدم التطبيق جهاز الصوت الافتراضي، ويمكن تغييره من إعدادات النظام عند الحاجة.</Text><GhostButton title="اختبار الصوت" onPress={() => Alert.alert("اختبار الصوت", "ستصبح قراءة الترجمة متاحة بعد ربط مزود الصوت الأصلي.")} /></View><View style={styles.card}><Text style={styles.cardTitle}>الخصوصية والموافقات</Text><View style={styles.row}><Text style={styles.rowText}>اسألني دائمًا قبل حفظ محتوى اجتماع جديد</Text><Switch value={storage} onValueChange={setStorage} trackColor={{ false: "#CBD5E1", true: colors.indigo }} /></View><View style={styles.row}><Text style={styles.rowText}>تذكير قبل الجلسات المجدولة</Text><Switch value={reminders} onValueChange={setReminders} trackColor={{ false: "#CBD5E1", true: colors.indigo }} /></View></View><PrimaryButton title="حفظ التغييرات" onPress={() => Alert.alert("حُفظ محليًا", "سيُزامن التطبيق هذه التفضيلات مع حسابك عند ربط API المنشور.")} /></ScrollView></Screen>; }
const styles = StyleSheet.create({ content: { padding: 20, gap: 16 }, top: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, eyebrow: { color: colors.indigo, fontSize: 11, fontWeight: "900" }, title: { color: colors.ink, fontSize: 31, fontWeight: "900", textAlign: "right" }, subtitle: { color: colors.muted, fontSize: 14, lineHeight: 23, textAlign: "right" }, card: { borderRadius: 22, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, padding: 17, gap: 13 }, cardTitle: { color: colors.ink, fontSize: 17, fontWeight: "900", textAlign: "right" }, choices: { flexDirection: "row", flexWrap: "wrap", justifyContent: "flex-end", gap: 8 }, choice: { paddingHorizontal: 12, paddingVertical: 9, borderWidth: 1, borderColor: colors.line, borderRadius: 10 }, selected: { borderColor: "#C7D2FE", backgroundColor: colors.lavender }, choiceText: { color: colors.muted, fontSize: 12, fontWeight: "700" }, selectedText: { color: colors.indigo }, note: { color: colors.muted, fontSize: 12, lineHeight: 20, textAlign: "right" }, row: { flexDirection: "row", justifyContent: "space-between", gap: 10, alignItems: "center", paddingVertical: 4 }, rowText: { flex: 1, color: colors.ink, fontSize: 13, lineHeight: 21, textAlign: "right" } });
